

Montant_mensuel_de_la_license = 490
NOMBRE_DE_MOIS_MAX_AUTORISER_POUR_LA_DEMANDE_DACTIVATION = 30
NOMBRE_MAX_DE_PC_POUR_UNE_MEME_CLE_PRODUIT = 75
TAUX_DE_RENTABILITE_DE_L_AFFILIE = 0.20
SOMME_MINIMALE_POUR_DE_L_AFFILIE = 1000
SOFT_KEY = b'BJHiemYoBsItsQiqi9g3DG3F_GGrovPKnNtt8vjgdt4='