# Generated by Django 5.1.3 on 2024-12-11 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activation', '0003_activation_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activation',
            name='id_of_installed_pc',
            field=models.CharField(default='', max_length=255),
        ),
    ]
