# Generated by Django 5.1.3 on 2024-12-15 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activation', '0007_activation_code_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='activation',
            name='number_of_pc',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
