# Generated by Django 5.1.3 on 2024-12-15 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activation', '0009_remove_activation_date_d_debut_d_uitlisation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activation',
            old_name='infos_of_all_installed_pc',
            new_name='infos_of_all_installed_pc_with_this_key',
        ),
    ]
