# Generated by Django 5.1.3 on 2024-12-22 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activation', '0013_activation_is_he_a_new_client_client_for_this_affilliate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SoftwareActivation',
        ),
    ]
