# Generated by Django 5.1.3 on 2024-12-22 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activation', '0015_initpayementoflicence_payement_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='initpayementoflicence',
            name='operateur_mobile',
            field=models.CharField(default='', max_length=60),
        ),
    ]
