# Generated by Django 5.1.3 on 2024-12-28 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activation', '0018_contactus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUs',
        ),
    ]
