# Generated by Django 5.1.3 on 2024-12-09 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activation',
            fields=[
                ('date_de_payement', models.DateTimeField(auto_now=True)),
                ('small_date_de_payement', models.DateField(auto_now=True)),
                ('who_many_months', models.PositiveSmallIntegerField(default=0)),
                ('is_expirated', models.CharField(choices=[('ACTIVEE', 'Activee'), ('ENCOUR', 'Encour'), ('EXPIREE', 'Expiree')], default='ACTIVEE', max_length=10)),
                ('product_key', models.CharField(default='', max_length=60, primary_key=True, serialize=False)),
                ('is_all_ready_used', models.BooleanField(default=False)),
                ('date_d_debut_d_uitlisation', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InitPayementOfLicence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_de_mois', models.PositiveSmallIntegerField(default=1)),
                ('date_of_initialise', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
