# Generated by Django 5.1.3 on 2024-12-09 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwareActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_key', models.TextField(default='')),
                ('id_of_installed_pc', models.TextField(default='')),
            ],
        ),
        migrations.AddField(
            model_name='activation',
            name='id_of_installed_pc',
            field=models.TextField(default=''),
        ),
    ]
