# Generated by Django 5.1.3 on 2024-12-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activation', '0006_alter_initpayementoflicence_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='activation',
            name='code_promo',
            field=models.CharField(default='aaaa', max_length=60),
        ),
    ]
