# Generated by Django 5.1.3 on 2024-12-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activation', '0008_activation_number_of_pc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activation',
            name='date_d_debut_d_uitlisation',
        ),
        migrations.RemoveField(
            model_name='activation',
            name='id_of_installed_pc',
        ),
        migrations.RemoveField(
            model_name='activation',
            name='is_all_ready_used',
        ),
        migrations.RemoveField(
            model_name='activation',
            name='serial_number',
        ),
        migrations.AddField(
            model_name='activation',
            name='infos_of_all_installed_pc',
            field=models.TextField(default='[]'),
        ),
    ]
