# Generated by Django 5.1.3 on 2024-12-15 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activation', '0010_rename_infos_of_all_installed_pc_activation_infos_of_all_installed_pc_with_this_key'),
        ('home', '0009_rename_nomber_of_free_days_myaffilliates_number_of_free_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='activation',
            name='affilliate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.myaffilliates'),
        ),
        migrations.AddField(
            model_name='activation',
            name='who_many_free_days',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
