# Generated by Django 5.1.3 on 2024-12-15 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activation', '0011_activation_affilliate_activation_who_many_free_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activation',
            name='code_promo',
        ),
        migrations.AddField(
            model_name='activation',
            name='somme_gagner_par_l_affilie',
            field=models.IntegerField(default=0),
        ),
    ]
