# Generated by Django 5.1.3 on 2024-12-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activation', '0012_remove_activation_code_promo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activation',
            name='is_he_a_new_client_client_for_this_affilliate',
            field=models.BooleanField(default=False),
        ),
    ]
