# Generated by Django 5.1.3 on 2024-12-24 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_user', '0010_delete_useractivation'),
        ('home', '0010_myaffilliates_solde'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetraitAffilie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=0)),
                ('numero_de_retrait', models.PositiveIntegerField()),
                ('date_de_demmande', models.DateTimeField(auto_now=True)),
                ('date_de_payement', models.DateTimeField()),
                ('status', models.CharField(choices=[('EN ATTENTE', 'En Attente'), ('PAYE', 'Paye'), ('ECHEC', 'Echec'), ('REFUSE', 'Refuse')], default='EN ATTENTE', max_length=30)),
                ('motif_du_gestionnaire', models.TextField(default='', max_length=255)),
                ('affiliete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.myaffilliates')),
            ],
        ),
    ]
