# Generated by Django 5.1.3 on 2024-12-24 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0011_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retraitaffilie',
            name='date_de_demmande',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
