# Generated by Django 5.1.3 on 2024-12-24 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0015_alter_retraitaffilie_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retraitaffilie',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
