# Generated by Django 5.1.3 on 2024-12-25 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0017_rename_date_de_payement_retraitaffilie_date_de_traitement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retraitaffilie',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
    ]
