# Generated by Django 5.1.3 on 2024-12-14 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_myaffilliate_code_affillie'),
    ]

    operations = [
        migrations.AddField(
            model_name='myaffilliate',
            name='his_client',
            field=models.TextField(default=''),
        ),
    ]
