# Generated by Django 5.1.3 on 2024-12-14 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_myaffilliate_his_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myaffilliate',
            old_name='his_client',
            new_name='his_clients',
        ),
    ]
