# Generated by Django 5.1.3 on 2024-12-15 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_myaffilliate_myaffilliates'),
    ]

    operations = [
        migrations.AddField(
            model_name='myaffilliates',
            name='nomber_of_free_days',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
