# Generated by Django 5.1.3 on 2024-12-22 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_nomber_of_free_days_myaffilliates_number_of_free_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='myaffilliates',
            name='solde',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
