# Generated by Django 5.1.3 on 2024-12-25 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_article_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myaffilliates',
            name='his_clients',
        ),
    ]
