# Generated by Django 5.1.3 on 2024-12-25 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_myaffilliates_his_clients'),
    ]

    operations = [
        migrations.AddField(
            model_name='telechargement',
            name='logo',
            field=models.ImageField(default='static/download/logos/default logo.png', upload_to='static/download/logos'),
        ),
        migrations.AlterField(
            model_name='telechargement',
            name='my_file',
            field=models.FileField(upload_to='static/download/files'),
        ),
    ]
