# Generated by Django 5.1.3 on 2024-12-26 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_telechargement_logo_alter_telechargement_my_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telechargement',
            name='logo',
            field=models.ImageField(default='static/download/logos/default logo.ico', upload_to='static/download/logos'),
        ),
    ]
