# Generated by Django 5.1.3 on 2024-12-05 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0007_alter_useractivation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivation',
            name='id_of_installed_pc',
            field=models.TextField(default=''),
        ),
    ]
