# Generated by Django 5.1.3 on 2024-12-09 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0008_useractivation_id_of_installed_pc'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivation',
            name='product_key',
            field=models.TextField(default=''),
        ),
    ]
