# Generated by Django 5.1.3 on 2024-12-22 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0009_useractivation_product_key'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserActivation',
        ),
    ]
