# Generated by Django 5.1.3 on 2024-12-24 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0012_alter_retraitaffilie_date_de_demmande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retraitaffilie',
            name='date_de_payement',
            field=models.DateTimeField(null=True),
        ),
    ]
