# Generated by Django 5.1.3 on 2024-12-24 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0013_alter_retraitaffilie_date_de_payement'),
    ]

    operations = [
        migrations.AddField(
            model_name='retraitaffilie',
            name='nom_du_beneficaire',
            field=models.CharField(default='VIDAL PAVER TSAFACK NANA', max_length=255),
        ),
    ]
