# Generated by Django 5.1.3 on 2024-12-24 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0014_retraitaffilie_nom_du_beneficaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retraitaffilie',
            name='amount',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
