# Generated by Django 5.1.3 on 2024-12-25 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0016_alter_retraitaffilie_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='retraitaffilie',
            old_name='date_de_payement',
            new_name='date_de_traitement',
        ),
    ]
