# Generated by Django 5.1.3 on 2024-11-24 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telechargement',
            name='my_file',
            field=models.FileField(upload_to='static/download'),
        ),
    ]
