# Generated by Django 5.1.3 on 2024-12-14 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_myaffilliate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myaffilliate',
            name='code_affillie',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
