# Generated by Django 5.1.3 on 2024-12-14 06:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_his_client_myaffilliate_his_clients'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyAffilliate',
            new_name='MyAffilliates',
        ),
    ]
