# Generated by Django 5.1.3 on 2024-12-15 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_myaffilliates_nomber_of_free_days'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myaffilliates',
            old_name='nomber_of_free_days',
            new_name='number_of_free_days',
        ),
    ]
